# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_liverpool_ion_data": "00_ingest_data.ipynb"}

modules = ["ingest_data.py"]

doc_url = "https://ImmoNathanael.github.io/time_series_segmentation/"

git_url = "https://github.com/ImmoNathanael/time_series_segmentation/tree/master/"

def custom_doc_links(name): return None
