# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_liverpool_ion_data": "00_data.ipynb",
         "add_seq_indicator": "01_feature_eng.ipynb",
         "dataframe_split": "01_feature_eng.ipynb",
         "feature_engineering_std": "01_feature_eng.ipynb",
         "feature_engineering_mean": "01_feature_eng.ipynb",
         "feature_engineering_drift": "01_feature_eng.ipynb"}

modules = ["data.py",
           "feature_eng.py"]

doc_url = "https://ImmoNathanael.github.io/time_series_segmentation/"

git_url = "https://github.com/ImmoNathanael/time_series_segmentation/tree/master/"

def custom_doc_links(name): return None
