# AUTOGENERATED! DO NOT EDIT! File to edit: 00_data.ipynb (unless otherwise specified).

__all__ = ['get_liverpool_ion_data']

# Cell
import pandas as pd
import os

from zipfile import ZipFile
from nbdev.showdoc import *

# Cell
def get_liverpool_ion_data():

    '''
    Gets data from Kaggle competition "University of Liverpool - Ion Switching Identify the number of channels open at each time point",
    URL: https://www.kaggle.com/c/liverpool-ion-switching/data

    This competition deals with time-step-wise segmentation.

    Requironments:
    -----------------------------------------------------------------
    Your kaggle API token has to be set up.


    Output:
    -----------------------------------------------------------------
    3 data frames:
    df_train: training data for the competition
    df_test: test data for competition submission
    df_sample: the kaggle submission sample format

    '''

    original_path = os.getcwd()

    try:
        os.mkdir(original_path + '\\data')
    except:
        print("data folder already exists")

    os.chdir(original_path+'\\data')


    # get the data from kaggel
    try:
        kaggle_data = os.popen('kaggle competitions download -c liverpool-ion-switching')
        kaggle_data.read()
    except:
        print('Is your kaggle API authentication set up correctly?')

    with ZipFile('liverpool-ion-switching.zip', 'r') as zipObj:
       # Extract all the data from kaggle in to corresponding folder
       zipObj.extractall("liverpool-ion-switching")

    os.chdir("../data/liverpool-ion-switching")

    df_train = pd.read_csv('train.csv')
    df_test = pd.read_csv('test.csv')
    df_sample = pd.read_csv('sample_submission.csv')
    os.chdir(original_path)

    return df_train, df_test, df_sample